//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 08:44:41 AM BST 
//

package gov.dvla.osg.scheduleCheck;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LastRun" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="AppSchedule" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FILE_PATTERN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EXPECTED" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DAYS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="MONTHS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="EARLIEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LATEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FAIL_MSG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "lastRun", "appSchedule" })
@XmlRootElement(name = "FileSchedule")
public class FileSchedule {

	@XmlElement(name = "LastRun", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar lastRun;
	@XmlElement(name = "AppSchedule", required = true)
	protected List<FileSchedule.AppSchedule> appSchedule;

	/**
	 * Gets the value of the lastRun property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getLastRun() {
		return lastRun;
	}

	/**
	 * Sets the value of the lastRun property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setLastRun(XMLGregorianCalendar value) {
		this.lastRun = value;
	}

	/**
	 * Gets the value of the appSchedule property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the appSchedule property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAppSchedule().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link FileSchedule.AppSchedule }
	 * 
	 * 
	 */
	public List<FileSchedule.AppSchedule> getAppSchedule() {
		if (appSchedule == null) {
			appSchedule = new ArrayList<FileSchedule.AppSchedule>();
		}
		return this.appSchedule;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="FILE_PATTERN" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="PATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="EXPECTED" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="DAYS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="MONTHS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="EARLIEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="LATEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="FAIL_MSG" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "filepattern", "path", "expected" })
	public static class AppSchedule {

		@XmlElement(name = "FILE_PATTERN", required = true)
		protected String filepattern;
		@XmlElement(name = "PATH", required = true)
		protected String path;
		@XmlElement(name = "EXPECTED", required = true)
		protected List<FileSchedule.AppSchedule.EXPECTED> expected;

		/**
		 * Gets the value of the filepattern property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFILEPATTERN() {
			return filepattern;
		}

		/**
		 * Sets the value of the filepattern property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setFILEPATTERN(String value) {
			this.filepattern = value;
		}

		/**
		 * Gets the value of the path property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPATH() {
			return path;
		}

		/**
		 * Sets the value of the path property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPATH(String value) {
			this.path = value;
		}

		/**
		 * Gets the value of the expected property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the expected property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getEXPECTED().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link FileSchedule.AppSchedule.EXPECTED }
		 * 
		 * 
		 */
		public List<FileSchedule.AppSchedule.EXPECTED> getEXPECTED() {
			if (expected == null) {
				expected = new ArrayList<FileSchedule.AppSchedule.EXPECTED>();
			}
			return this.expected;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="DAYS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="MONTHS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="EARLIEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="LATEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="FAIL_MSG" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "days", "months", "earliest", "latest", "failmsg" })
		public static class EXPECTED {

			@XmlElement(name = "DAYS")
			protected String days;
			@XmlElement(name = "MONTHS")
			protected String months;
			@XmlElement(name = "EARLIEST", required = true)
			protected String earliest;
			@XmlElement(name = "LATEST", required = true)
			protected String latest;
			@XmlElement(name = "FAIL_MSG", required = true)
			protected String failmsg;

			@XmlTransient
			private Boolean reported = false;

			/**
			 * Gets the value of the days property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDAYS() {
				return days;
			}

			public void setReported(Boolean value) {
				this.reported = value;
			}

			public Boolean getReported() {
				return reported;
			}

			/**
			 * Sets the value of the days property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setDAYS(String value) {
				this.days = value;
			}

			/**
			 * Gets the value of the months property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMONTHS() {
				return months;
			}

			/**
			 * Sets the value of the months property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setMONTHS(String value) {
				this.months = value;
			}

			/**
			 * Gets the value of the earliest property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getEARLIEST() {
				return earliest;
			}

			/**
			 * Sets the value of the earliest property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setEARLIEST(String value) {
				this.earliest = value;
			}

			/**
			 * Gets the value of the latest property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLATEST() {
				return latest;
			}

			/**
			 * Sets the value of the latest property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setLATEST(String value) {
				this.latest = value;
			}

			/**
			 * Gets the value of the failmsg property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFAILMSG() {
				return failmsg;
			}

			/**
			 * Sets the value of the failmsg property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setFAILMSG(String value) {
				this.failmsg = value;
			}

		}

	}

}
