//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.20 at 08:44:41 AM BST 
//


package gov.dvla.osg.scheduleCheck;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.dvla.osg.scheduleCheck package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.dvla.osg.scheduleCheck
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileSchedule }
     * 
     */
    public FileSchedule createFileSchedule() {
        return new FileSchedule();
    }

    /**
     * Create an instance of {@link FileSchedule.AppSchedule }
     * 
     */
    public FileSchedule.AppSchedule createFileScheduleAppSchedule() {
        return new FileSchedule.AppSchedule();
    }

    /**
     * Create an instance of {@link FileSchedule.AppSchedule.EXPECTED }
     * 
     */
    public FileSchedule.AppSchedule.EXPECTED createFileScheduleAppScheduleEXPECTED() {
        return new FileSchedule.AppSchedule.EXPECTED();
    }

}
